version = 0.1

[default.build.parameters]
use_container = false

[default.deploy.parameters]
stack_name = "rightapply-backend"
region = "us-east-1"
resolve_s3 = true
s3_prefix = "rightapply-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
